---
title: "Exploring eDNA in SBDI"
format:
  html:
    toc: false
---

Welcome to the **Exploring eDNA in SBDI** workshop at
[SBDI Days 2026](https://lyyti.events/p/SBDI_Days_2026__Artificial_Intelligence_in_Ecology_and_Biodiversity_Research_9077)!

## Description
This workshop will demonstrate how environmental DNA (eDNA) / metabarcoding data can be accessed, processed, and analyzed within the [Swedish Biodiversity Data Infrastructure (SBDI)](https://biodiversitydata.se/). We will show how to download eDNA data, use our R package to unpack, merge, and aggregate datasets, and then explore biodiversity patterns across environments in R. The session will also introduce SBDI resources for data submission, processing, and integration with GBIF.

## Expected outcomes
Participants will learn about tools and workflows for eDNA data management and analysis, and how these contribute to open biodiversity knowledge.

## Instructors
- Prof. Anders Andersson — SBDI & KTH SciLifeLab
- Dr. Daniel Lundin — SBDI & Linnaeus University
- Dr. Maria Prager — SBDI & University of Gothenburg
- Karin Garefelt - KTH SciLifeLab
- Krzysztof Jurdzinski - KTH SciLifeLab
- Dr. Emma Bell - SU SciLifeLab
