---
title: "1. Set up the environment"
format:
  html:
    toc: false
---

*Set up the R environment used in the tutorial, either via the workshop cloud environment or locally on your laptop.*

## Option A (recommended): Workshop RStudio environment

A virtual machine running RStudio Server is available in PDC Cloud.
Log in using the credentials provided during the workshop:

[RStudio Server](http://193.10.159.112:8787){target="_blank"}

Follow the tutorial steps and **avoid creating additional large objects**, as resources are shared. Save your work regularly as an R script. The virtual machine will be shut down after the workshop, so download any code or output you want to keep via the Files pane (More → Export).

### Check required packages

Load `asvoccur` and confirm version:

```r
library(asvoccur)
packageVersion("asvoccur")  # Should say 1.1.1
```

### Check access to example data {#check-access}

For this tutorial, ASV portal data is pre-downloaded and available on the virtual machine. Check access:

```r
data_path <- "/srv/course-data/16S"
list.files(data_path)
```

If two (16S) zip files are listed, you are ready to proceed.

## Option B (fallback): Run RStudio locally on your laptop

Our cloud environment is being tested for the first time. If needed, you can run the tutorial locally.

You will need to install:

1. [R](https://cran.r-project.org/){target="_blank"}<br>
2. [RStudio](https://posit.co/download/rstudio-desktop/){target="_blank"}
3. the `remotes` and `asvoccur` R packages

To install the required R packages:

```r
install.packages('remotes')
remotes::install_github("biodiversitydata-se/asvoccur")
library(asvoccur)
packageVersion("asvoccur")  # Should say 1.1.1
```

### Download example data from the ASV portal

In this option, example data is downloaded directly from the ASV portal.

1. Go to the [ASV portal start page](https://asv-portal.biodiversitydata.se/index){target="_blank"}.

   Click **DOWNLOAD**. If you are not already logged in, you will be redirected to the login page.

2. If you do not already have an account, either:
   - sign in with a Google or GitHub account, or
   - create a new SBDI account.

3. On the **Download** page, under **Download link**, download the following datasets
   (**note** the underlined project IDs to distinguish similar titles):

   - PRJEB552**<ins>96</ins>**-16S
   - KTH-2013-Baltic-16S
   - PRJEB552**<ins>96</ins>**-18S
   - KTH-2013-Baltic-18S

4. After downloading, organise the data locally into two separate folders:

       course-data/
       ├── 16S/
       │   ├── PRJEB55296-16S.zip
       │   └── KTH-2013-Baltic-16S.zip
       └── 18S/
           ├── PRJEB55296-18S.zip
           └── KTH-2013-Baltic-18S.zip

5. Set the path to the 16S data folder in R and confirm access:
```r
       data_path <- "local/path/to/course-data/16S"
       list.files(data_path)
```

[Overview](tutorial.qmd) · [Next →](tutorial-02-prep.qmd)